#!/usr/bin/env bash

# long wait
docker exec grid versions || true
docker exec grid stop || true
docker stop grid || true
docker rm grid || true
# quick destroy
docker rm -vf grid_mock || true

docker stop grid_x_user || true
docker rm grid_x_user || true
