#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e

# long wait
docker exec grid stop || true
docker stop grid || true
docker rm grid || true
# quick destroy
docker rm -vf grid_mock || true
