#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

echoerr() { printf "%s\n" "$*" >&2; }

# print error and exit
die () {
  echoerr "ERROR: $1"
  # if $2 is defined AND NOT EMPTY, use $2; otherwise, set to "150"
  errnum=${2-133}
  exit $errnum
}

docker --version
docker-compose --version

[ "${TRAVIS_BUILD_NUMBER}" == "" ] && die "Need env var TRAVIS_BUILD_NUMBER to know where to pull from"

docker pull elgalu/build_selenium:${TRAVIS_BUILD_NUMBER}
docker tag elgalu/build_selenium:${TRAVIS_BUILD_NUMBER} selenium:latest
docker images selenium
