#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e

# Install docker compose
#  https://docs.travis-ci.com/user/docker/#Using-Docker-Compose
sudo rm -f /usr/local/bin/docker-compose
curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
chmod +x docker-compose
sudo mv docker-compose /usr/local/bin

docker-compose --version
