#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e

docker --version || echo "INFO: No docker installed yet"

sudo ./test/before_install_docker

docker --version || (echo "FATAL: No docker installed" && exit 1)
