#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

# Docker
docker --version || echo "INFO: No docker installed yet"
if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
  ./test/before_install_docker_osx
else
  sudo -E bash -c './test/before_install_docker_linux'
fi
docker --version || (echo "FATAL: No docker installed" && exit 1)

# Docker Compose
if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
  echo "OSX should already have docker-compose installed via docker toolbox"
else
  docker-compose --version || echo "INFO: No docker compose installed yet"
  sudo -E bash -c './test/before_install_docker_compose'
fi
docker-compose --version || (echo "FATAL: No docker compose installed" && exit 1)

# Notes:
#  sudo -E or --preserve-env will preserve travis env vars like DOCKER_COMPOSE_VERSION
