#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

docker --version
docker-compose --version

./host-scripts/gen-scm-source.sh

docker build -t selenium .
docker images selenium
