#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

[ "${TRAVIS_OS_NAME}" = "osx" ] && eval "$(docker-machine env default)" || true

# Ensure clean env
docker rm -vf grid || true
docker rm -vf grid_adwords_mock || true

docker run --name=grid -d -e VIDEO=true -v /dev/shm:/dev/shm selenium

# We need a mock service for testing
docker run -d --name=grid_adwords_mock --net=container:grid elgalu/google_adwords_mock

docker exec grid wait_all_done 40s
docker exec grid versions
docker exec grid errors || true
docker logs grid

docker tag selenium:latest elgalu/selenium:latest
