#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

[ "${TRAVIS_OS_NAME}" = "osx" ] && eval "$(docker-machine env default)" || true

export TESTING="true"

./test/script_bats
./test/script_scenario_basic
./test/script_scenario_restart
./test/script_scenario_node_dies
./test/script_scenario_make
