#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e

echo "#=================="
echo "# Archive artifacts"
echo "#=================="
# pending to upload to S3 bucket
docker cp grid:/test/console.png ./images/grid3_console.png
ls -la ./images/
mkdir -p ./videos
docker cp grid:/test/videos/chrome ./videos/
docker cp grid:/test/videos/firefox ./videos/
docker cp grid:/test/videos/mobile_emulation ./videos/
ls -la ./videos/chrome
ls -la ./videos/firefox
ls -la ./videos/mobile_emulation
ls -la ./videos/
