#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

echo "#======================================================="
echo "# Scenario 3: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#======================================================="
export NUM_NODES=1 PARAL_TESTS=1 SELENIUM_HUB_PORT="4444"
./test/compose-test.sh
