#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

echo "#======================================="
echo "# Scenario 4: Docker Compose many nodes"
echo "#======================================="
export SELENIUM_HUB_PORT="4444"

if [ "${TRAVIS}" = "true" ]; then
  export NUM_NODES=2 PARAL_TESTS=2 WAIT_ALL_DONE="390s"
else
  # My local laptop has more power so hit it harder
  export NUM_NODES=7 PARAL_TESTS=7 WAIT_ALL_DONE="90s"
fi

./test/compose-test.sh
