#!/usr/bin/env bash

echo "#===================================================="
echo "# Scenario 6a [compose_N_N]: Docker Compose many nodes"
echo "#===================================================="

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

export VNC_FROM_PORT="43900" VNC_TO_PORT="43950"

if [ "${CI}" = "true" ]; then
  export NUM_NODES=2 PARAL_TESTS=2 WAIT_ALL_DONE="390s" SLEEP_TIME=10 PAUSE_SECS_BETWEEN_RUN_TEST="0"
else
  export NUM_NODES=4 PARAL_TESTS=4 WAIT_ALL_DONE="390s" SLEEP_TIME=10 PAUSE_SECS_BETWEEN_RUN_TEST="0"
fi

export COMPOSE_FILE="docker-compose-host.yml" \
       DO_COMPOSE_UP="false"
./test/compose-test.sh

echo "#===================================================="
echo "# Scenario 6b [compose_N_N]: Docker Compose many nodes"
echo "#===================================================="
export VNC_FROM_PORT="26950" VNC_TO_PORT="26999"
export COMPOSE_FILE="docker-compose.yml" \
       DO_COMPOSE_UP="true"
./test/compose-test.sh
