#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

[ "${TRAVIS_OS_NAME}" = "osx" ] && eval "$(docker-machine env default)" || true

./test/script_scenario_compose_N_N
