#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
set -e

echo "#=============================================================="
echo "# Scenario 2: Forced quick container restart + run tests again"
echo "#=============================================================="
docker restart --time=0 grid #forced quick restart
sleep 3 #to avoid issue #83
docker exec grid wait_all_done 40s
docker exec grid errors || true
docker exec -ti grid run_test
docker logs grid
