#!/usr/bin/env bash

echo "#===================================================================="
echo "# Scenario 4a [compose_1_1]: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#===================================================================="

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
# set -u: treat unset variables as an error and exit immediately
set -xe

export SELENIUM_HUB_PORT="4444" \
       NUM_NODES=1 PARAL_TESTS=1 \
       VNC_FROM_PORT="40650" VNC_TO_PORT="40700"

# Below sleep avoids:
#  Error forwarding the new session cannot find : Capabilities ...
if [ "${CI}" = "true" ]; then
  export SLEEP_TIME=15
else
  export SLEEP_TIME=4
fi

export COMPOSE_FILE="docker-compose-host.yml" \
       DO_COMPOSE_UP="false"
./test/compose-test.sh

echo "#===================================================================="
echo "# Scenario 4b [compose_1_1]: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#===================================================================="
export COMPOSE_FILE="docker-compose.yml" \
       DO_COMPOSE_UP="true"
./test/compose-test.sh
