#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

echo "#======================================================="
echo "# Scenario 3: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#======================================================="
export SELENIUM_HUB_PORT="4444" NUM_NODES=1 PARAL_TESTS=1

if [ "${TRAVIS}" = "true" ]; then
  export SLEEP_TIME=7
else
  # My local laptop has more power so hit it harder
  export SLEEP_TIME=0
fi

./test/compose-test.sh
