#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

rm -rf ./videos ./tmp_videos
./test/script_bats

# In Travis these ones require travis_retry
if [ "${CI}" != "true" ]; then
  ./test/script_scenario_basic
  ./test/script_scenario_arbitrary_uid
  ./test/script_scenario_restart
  ./test/script_scenario_node_dies
  ./test/script_scenario_compose_N_N
  ./test/script_scenario_zalenium
fi
