#!/usr/bin/env bash

echo "#===================================================================="
echo "# Scenario 5a [compose_1_1]: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#===================================================================="

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
# set -u: treat unset variables as an error and exit immediately
set -xe

export NUM_NODES=1 PARAL_TESTS=1 \
       VNC_FROM_PORT="41800" VNC_TO_PORT="41850" \
       VIDEO="false"

# Below sleep avoids:
#  Error forwarding the new session cannot find : Capabilities ...
if [ "${CI}" = "true" ]; then
  export SLEEP_TIME=15
else
  export SLEEP_TIME=4
fi

export COMPOSE_FILE="docker-compose-host.yml" \
       DO_COMPOSE_UP="false"
./test/compose-test.sh

echo "#===================================================================="
echo "# Scenario 5b [compose_1_1]: Docker Compose 1 hub, 1 chrome, 1 firefox"
echo "#===================================================================="
export VNC_FROM_PORT="61900" VNC_TO_PORT="61950"
export COMPOSE_FILE="docker-compose.yml" \
       DO_COMPOSE_UP="true"
./test/compose-test.sh
