#!/usr/bin/env bash

echo "#===================================================="
echo "# Scenario 5 [compose_N_N]: Docker Compose many nodes"
echo "#===================================================="

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

export SELENIUM_HUB_PORT="4444"

if [ "${TRAVIS}" = "true" ]; then
  export NUM_NODES=2 PARAL_TESTS=2 WAIT_ALL_DONE="390s" SLEEP_TIME=17
else
  # My local laptop has more power so hit it harder
  export NUM_NODES=6 PARAL_TESTS=6 WAIT_ALL_DONE="90s" SLEEP_TIME=10
fi

./test/compose-test.sh
