#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

[ "${TRAVIS_OS_NAME}" = "osx" ] && eval "$(docker-machine env default)" || true

rm -rf ./videos
./test/script_bats
./test/script_scenario_basic
./test/script_scenario_restart
./test/script_scenario_node_dies

# In Travis these ones require travis_retry
# TODO: fix flakiness
if [ "${CI}" != "true" ]; then
  ./test/script_scenario_make
  ./test/script_scenario_compose_1_1
  ./test/script_scenario_compose_N_N
fi
