#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

./test/script_bats
./test/script_scenario_basic
./test/script_scenario_restart
# ./test/script_scenario_node_dies
./test/script_scenario_compose_1_1
./test/script_scenario_compose_N_N
./test/script_archive
./test/script_push
