#!/usr/bin/env bash

# set -e: exit asap if a command exits with a non-zero status
# set -x: print each command right before it is executed
set -xe

./test/script_bats
./test/script_scenario_1
./test/script_scenario_2
./test/script_scenario_3
./test/script_scenario_4
./test/script_archive
./test/script_push
